### ISSUE TITLE
コンパイルファイルって載せるもんなのか

### ISSUE THREAD

**Issue by shimonosatoru** [shimonosatoru/golang-template#4]

**Comment by uma-co82** [comment]
どうなんだろ、、
swiftもコンパイルしたら
> ./sample.out

みたいなファイル作成されます

**Comment by shimonosatoru** [comment]
論点としては
#### devsolmu-coreのディレクトリ名に基づいてコンパイルファイルが生成されるので人によって違う
ということで人によって違うものは基本的にgit上にはあげない方がよく、それはpushしない方針でやる方がいいのか何かもっといい方法があるのかといった感じです。
